declare const IsGame: (str: string) => boolean
declare const GetExtraColorThreshold: () => number
declare const AllowOptionsMenu: () => boolean
declare const GameCompatibleModes: () => string
declare const ScreenSelectStyleChoices: () => AnyTable
declare const ScreenSelectStylePositions: (count: number) => AnyTable
declare const SelectProfileKeys: () => string
declare const ComboContinue: () => string
declare const ComboMaintain: () => string
declare const ComboPerRow: () => boolean
declare const EvalUsesCheckpointsWithJudgments: () => boolean
declare const HitCombo: () => number
declare const MissCombo: () => number
declare const FailCombo: () => number
declare const TwoPartSelection: () => boolean
declare const RoutineSkinP1: () => string
declare const RoutineSkinP2: () => string
declare const HoldTiming: () => number
declare const ShowHoldJudgments: () => boolean
declare const GetCodeForGame: (codeName: string) => string
declare const GetOptionsListMapping: (name: string) => string
declare const oitg_zoom_mode_actor: () => Actor